version: '3.7'
services:
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"
    depends_on :
      - mariadb

  apache:
    build: .
    volumes:
      - ./phpFile:/var/www/monsite/phpFile
    ports:
      - "80:80"




